services:
  db:
    image: postgres:15-alpine
    container_name: painter_bot_db
    environment:
      POSTGRES_DB: painter_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      # Настройки для стабильности соединений
      POSTGRES_SHARED_PRELOAD_LIBRARIES: "pg_stat_statements"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d painter_bot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: >
      postgres -c max_connections=200 -c shared_buffers=256MB -c effective_cache_size=1GB -c maintenance_work_mem=64MB -c checkpoint_completion_target=0.9 -c wal_buffers=16MB -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200 -c work_mem=4MB -c min_wal_size=1GB -c max_wal_size=4GB -c tcp_keepalives_idle=600 -c tcp_keepalives_interval=30 -c tcp_keepalives_count=3 -c statement_timeout=60s -c lock_timeout=30s -c idle_in_transaction_session_timeout=300s

  bot:
    build: .
    container_name: painter_bot
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - MODERATION_CHAT_ID=${MODERATION_CHAT_ID}
      - PAINTER_TOPIC_ID=${PAINTER_TOPIC_ID}
      - SANDBLASTER_TOPIC_ID=${SANDBLASTER_TOPIC_ID}
      # Цены за одиночные диски
      - PRICE_SINGLE_R12=${PRICE_SINGLE_R12:-150}
      - PRICE_SINGLE_R13=${PRICE_SINGLE_R13:-200}
      - PRICE_SINGLE_R14=${PRICE_SINGLE_R14:-300}
      - PRICE_SINGLE_R15=${PRICE_SINGLE_R15:-300}
      - PRICE_SINGLE_R16=${PRICE_SINGLE_R16:-400}
      - PRICE_SINGLE_R17=${PRICE_SINGLE_R17:-500}
      - PRICE_SINGLE_R18=${PRICE_SINGLE_R18:-700}
      - PRICE_SINGLE_R19=${PRICE_SINGLE_R19:-900}
      - PRICE_SINGLE_R20=${PRICE_SINGLE_R20:-1100}
      - PRICE_SINGLE_R21=${PRICE_SINGLE_R21:-1200}
      - PRICE_SINGLE_R22=${PRICE_SINGLE_R22:-1200}
      - PRICE_SINGLE_R23=${PRICE_SINGLE_R23:-1300}
      - PRICE_SINGLE_R24=${PRICE_SINGLE_R24:-1500}
      # Цены за комплекты
      - PRICE_SET_R12=${PRICE_SET_R12:-600}
      - PRICE_SET_R13=${PRICE_SET_R13:-700}
      - PRICE_SET_R14=${PRICE_SET_R14:-700}
      - PRICE_SET_R15=${PRICE_SET_R15:-800}
      - PRICE_SET_R16=${PRICE_SET_R16:-800}
      - PRICE_SET_R17=${PRICE_SET_R17:-1000}
      - PRICE_SET_R18=${PRICE_SET_R18:-1200}
      - PRICE_SET_R19=${PRICE_SET_R19:-1400}
      - PRICE_SET_R20=${PRICE_SET_R20:-1600}
      - PRICE_SET_R21=${PRICE_SET_R21:-1800}
      - PRICE_SET_R22=${PRICE_SET_R22:-2000}
      - PRICE_SET_R23=${PRICE_SET_R23:-2200}
      - PRICE_SET_R24=${PRICE_SET_R24:-2500}
      # Доплата за подготовку
      - PRICE_PREP_SINGLE=${PRICE_PREP_SINGLE:-210}
      - PRICE_PREP_SET=${PRICE_PREP_SET:-300}
      # Доплата за алюмохром
      - PRICE_ALUMOCHROME_EXTRA=${PRICE_ALUMOCHROME_EXTRA:-300}
      # Цены за новые типы заказов (для маляра)
      - PRICE_NAKIDKA=${PRICE_NAKIDKA:-300}
      - PRICE_SUSPENSIA_PAINT=${PRICE_SUSPENSIA_PAINT:-750}
      - PRICE_SUSPENSIA_LOGO=${PRICE_SUSPENSIA_LOGO:-875}
      # Цены для пескоструйщика - комплекты
      - PRICE_SANDBLASTER_SET_R12=${PRICE_SANDBLASTER_SET_R12:-600}
      - PRICE_SANDBLASTER_SET_R13=${PRICE_SANDBLASTER_SET_R13:-700}
      - PRICE_SANDBLASTER_SET_R14=${PRICE_SANDBLASTER_SET_R14:-700}
      - PRICE_SANDBLASTER_SET_R15=${PRICE_SANDBLASTER_SET_R15:-700}
      - PRICE_SANDBLASTER_SET_R16=${PRICE_SANDBLASTER_SET_R16:-820}
      - PRICE_SANDBLASTER_SET_R17=${PRICE_SANDBLASTER_SET_R17:-820}
      - PRICE_SANDBLASTER_SET_R18=${PRICE_SANDBLASTER_SET_R18:-940}
      - PRICE_SANDBLASTER_SET_R19=${PRICE_SANDBLASTER_SET_R19:-1200}
      - PRICE_SANDBLASTER_SET_R20=${PRICE_SANDBLASTER_SET_R20:-1200}
      - PRICE_SANDBLASTER_SET_R21=${PRICE_SANDBLASTER_SET_R21:-1200}
      - PRICE_SANDBLASTER_SET_R22=${PRICE_SANDBLASTER_SET_R22:-1600}
      - PRICE_SANDBLASTER_SET_R23=${PRICE_SANDBLASTER_SET_R23:-1800}
      - PRICE_SANDBLASTER_SET_R24=${PRICE_SANDBLASTER_SET_R24:-2000}
      # Цены для пескоструйщика - одиночки
      - PRICE_SANDBLASTER_SINGLE_R12=${PRICE_SANDBLASTER_SINGLE_R12:-150}
      - PRICE_SANDBLASTER_SINGLE_R13=${PRICE_SANDBLASTER_SINGLE_R13:-175}
      - PRICE_SANDBLASTER_SINGLE_R14=${PRICE_SANDBLASTER_SINGLE_R14:-175}
      - PRICE_SANDBLASTER_SINGLE_R15=${PRICE_SANDBLASTER_SINGLE_R15:-175}
      - PRICE_SANDBLASTER_SINGLE_R16=${PRICE_SANDBLASTER_SINGLE_R16:-205}
      - PRICE_SANDBLASTER_SINGLE_R17=${PRICE_SANDBLASTER_SINGLE_R17:-205}
      - PRICE_SANDBLASTER_SINGLE_R18=${PRICE_SANDBLASTER_SINGLE_R18:-235}
      - PRICE_SANDBLASTER_SINGLE_R19=${PRICE_SANDBLASTER_SINGLE_R19:-300}
      - PRICE_SANDBLASTER_SINGLE_R20=${PRICE_SANDBLASTER_SINGLE_R20:-300}
      - PRICE_SANDBLASTER_SINGLE_R21=${PRICE_SANDBLASTER_SINGLE_R21:-300}
      - PRICE_SANDBLASTER_SINGLE_R22=${PRICE_SANDBLASTER_SINGLE_R22:-400}
      - PRICE_SANDBLASTER_SINGLE_R23=${PRICE_SANDBLASTER_SINGLE_R23:-450}
      - PRICE_SANDBLASTER_SINGLE_R24=${PRICE_SANDBLASTER_SINGLE_R24:-500}
      # Цены для пескоструйщика - другие типы
      - PRICE_SANDBLASTER_NAKIDKA=${PRICE_SANDBLASTER_NAKIDKA:-150}
      - PRICE_SANDBLASTER_SUSPENSIA=${PRICE_SANDBLASTER_SUSPENSIA:-305}
      # Цены за напыление для пескоструйщика
      - PRICE_SPRAYING_DEEP=${PRICE_SPRAYING_DEEP:-537}
      - PRICE_SPRAYING_SHALLOW=${PRICE_SPRAYING_SHALLOW:-237}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=painter_bot
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
